INSERT INTO books (name, author, genre, about) VALUES ('Life Of Pie', 'Yann Martel','Fantasy Adventure','Life of Pi is a fantasy adventure novel by Yann Martel published in 2001. The protagonist, Piscine Molitor "Pi" Patel, a Tamil boy from Pondicherry, explores issues of spirituality and practicality from an early age. He survives 227 days after a shipwreck while stranded on a boat in the Pacific Ocean with a Bengal tiger named Richard Parker.');

INSERT INTO books (name, author, genre, about) VALUES ('Rot and Ruin','Jonathan Maberry', 'Science Fiction', 'In the zombie-infested, post-apocalyptic America where Benny Imura lives, every teenager must find a job by the time they turn fifteen or get their rations cut in half. Benny does not want to apprentice as a zombie hunter with his boring older brother Tom, but he has no choice. He expects a tedious job whacking zoms for cash, but what he gets is a vocation that will teach him what it means to be human.');

INSERT INTO books (name, author, genre, about) VALUES('Pride and Prejudice', 'Jane Austen', 'Romance','The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness. Its humour lies in its honest depiction of manners, education, marriage, and money during the Regency era in Great Britain.');

INSERT INTO books (name, author, genre, about) VALUES('House Lessons: Renovating a Life','Erica Bauermeister', 'Memoir', 'In this mesmerizing memoir-in-essays, Erica Bauermeister renovates a trash-filled house in eccentric Port Townsend, Washington, and in the process takes readers on a journey to discover the ways our spaces subliminally affect us. A personal, accessible, and literary exploration of the psychology of architecture, as well as a loving tribute to the connections we forge with the homes we care for and live in, this book is designed for anyone who’s ever fallen head over heels for a house. It is also a story of a marriage, of family, and of the kind of roots that settle deep into your heart. Discover what happens when a house has its own lessons to teach in this moving and insightful memoir that ultimately shows us how to make our own homes (and lives) better.');

INSERT INTO books (name, author, genre, about) VALUES('The Fault In Our Stars', 'John Green', 'Romance', 'Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazels story is about to be completely rewritten.');

INSERT INTO books (name, author, genre, about) VALUES('The Guest List', 'Lucy Foley', 'Thriller', 'Set on a remote island off the Irish coast, this is one guest list no one would want to be on, just as no one would have wanted an invitation to the New Year Eve party in Foleys previous novel, The Hunting Party . Lives unravel amid the revelry on an eerie and remote island as family and friends assemble for a glam wedding in an updated Murder on the Orient Express. Each of the principal characters has a reason to want one of their number dead, there are old secrets, and one of them is murdered.');

INSERT INTO books (name, author, genre, about) VALUES('Shake Down', 'Kendel Lynn', 'Thriller','Ballantyne Foundation Director and PI-in-training, Elliott Lisbon, is enjoying her idyllically slow life on Sea Pine Island, South Carolina. It is the week before the annual Beach Ball and she is sipping Bellinis on the sidelines. Her committee involvement is limited to securing the centerpieces: scrumptious two-tiered masterpieces from the Cake & Shake. But when the head baker goes missing, Elli’s calm life gets a major shakeup. She takes the case and soon learns that missing is a relative term. These two bffs were once rivals on a local dating show. Perhaps the free spirit had reason to wander off on her own. Or perhaps she wasn’t the only woman scorned. As Elli walks the delicate line between a woman finding herself and a woman needing to be found, the days speed up and she knows something is about to go down. From drug runners to whistle-blowers to sea turtle sabotage, Elli stirs up secrets and inadvertently whips a desperate killer into a frenzy. If she does not find a way out of the heat, she is going to get burned.');

INSERT INTO books (name, author, genre, about) VALUES('Eclipse', 'Stephanie Meyer', 'Romance', 'As Seattle is ravaged by a string of mysterious killings and a malicious vampire continues her quest for revenge, Bella once again finds herself surrounded by danger. In the midst of it all, she is forced to choose between her love for Edward and her friendship with Jacob - knowing that her decision has the potential to ignite the ageless struggle between vampire and werewolf. With her graduation quickly approaching, Bella has one more decision to make: life or death. But which is which?');
INSERT INTO books (name, author, genre, about) VALUES('The Namesake', 'jhumpa Lahiri', 'Contemporary', 'The Namesake takes the Ganguli family from their tradition-bound life in Calcutta through their fraught transformation into Americans. On the heels of their arranged wedding, Ashoke and Ashima Ganguli settle together in Cambridge, Massachusetts. An engineer by training, Ashoke adapts far less warily than his wife, who resists all things American and pines for her family. When their son is born, the task of naming him betrays the vexed results of bringing old ways to the new world. Named for a Russian writer by his Indian parents in memory of a catastrophe years before, Gogol Ganguli knows only that he suffers the burden of his heritage as well as his odd, antic name.');
INSERT INTO books (name, author, genre, about) VALUES('The City We Became', 'N.K.Jemisin','Fiction', 'Every city has a soul. Some are as ancient as myths, and others are as new and destructive as children. New York City? She has got five. But every city also has a dark side. A roiling, ancient evil stirs beneath the earth, threatening to destroy the city and her five protectors unless they can come together and stop it once and for all.');